###################################################
# BUILT-IN CONFIGURATION OPTOINS                  #
# https://gohugo.io/getting-started/configuration #
###################################################

baseURL = "https://zsolt2106.github.io/zsoltfedor-webpage/" # website root path
disqusShortname = ""                      # disqus shortcode
enableGitInfo = false                     # retrieve last modified date from git commits
enableRobotsTXT = true                    # /robots.txt
googleAnalytics = ""                      # google analytics id
hasCJKLanguage = false                    # Chinese/Japanese/Korean
languageCode = "en"                       # content language
paginate = 5                              # number of posts each page
rssLimit = 10                             # maximum items in rss feeds
theme = "hugo-theme-texify"               # theme directory name
title = "Zsolt Fedor"                     # website title


# https://gohugo.io/getting-started/configuration-markup
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true # enable html in markdown
[markup.highlight]
style = "emacs" # syntax highlight style, see https://xyproto.github.io/splash/docs/

[permalinks]
   post ="homepage/:slug"

# https://gohugo.io/content-management/menus/
[[menu.main]]
identifier = "index" # section id
name = "Home"       # section display title
url = "/"           # path to the section
weight = 1          # order of sections
[[menu.main]]
identifier = "projects"
name = "My Projects"
url = "/projects/"
weight = 2
[[menu.main]]
identifier = "about"
name = "About me"
url = "/about"
weight = 3

# https://gohugo.io/content-management/taxonomies#configure-taxonomies
[taxonomies]
series = "series" # see https://gohugo.io/templates/internal/#open-graph
tags = "tags"


########################
# TEXIFY THEME OPTIONS #
########################

[params]
description = "my website with hugo theme TeXify" # website description
favicon = "favicon.ico" # path to website icon, relative to ./static
footnote = """
""" # notes in the website footer
keywords = ["hugo", "latex", "theme"] # website keywords

customCSS = ["styles.css"]            # path to custom css files, relative to ./static
customJS = []             # path to custom js files, relative to ./static
dateFormat = "2006-01-02" # date format, see https://gohugo.io/functions/format/
fullTextRSS = true        # output full-text (instead of only summary) rss
emphasisWithDots = true   # use dots to emphasize chinese texts, see https://zh.wikipedia.org/wiki/%E7%9D%80%E9%87%8D%E5%8F%B7
since = "I own nothing, feel free to copy anything you see."            # website created year
toc = false               # whether to enable table of contents in posts

# https://giscus.app
[params.giscus]
enable = false # whether to enable giscus
# paste giscus' <script></script> configuration between the triple quotes
script = """
"""

[params.math]
enable = false # whether to enable math typesetting
use = "katex"  # katex or mathjax

[params.outdated]
enable = false # whether to display warnings for outdated posts
limit = 1000   # days between last modified time and outdated time
# warning to be displayed
warning = "⚠️ It has been <i>%d</i> days since the last update, the content of the article may be outdated."

# https://utteranc.es
[params.utterances]
enable = false # whether to enable utterances
# paste utterances' <script></script> configuration between the triple quotes
script = """
"""
